owner: crossid
repo: status

sites:
  - name: US production cluster
    url: https://crossid.us.crossid.io/api/cluster/v1/health/ready
  - name: US preview cluster
    url: https://crossid.us.preview.crossid.io/api/cluster/v1/health/ready
  - name: US development cluster
    url: https://crossid.us.dev.crossid.io/api/cluster/v1/health/ready
  - name: Crossid.io
    url: https://crossid.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.crossid.io
  # baseUrl: /your-repo-name
  logoUrl: https://crossid.io/favicon.ico
  name: Crossid Status
  introTitle: "Uptime and status page."
  introMessage: This is a status page of [crossid](https://crossid.io) infrastructure
  navbar:
    - title: Status
      href: /
    - title: crossid.io
      href: https://crossid.io
  i18n:
    footer: Status page [crossid.io](https://crossid.io)
